const sampleListings = [
  { title: "Cozy Beachfront Cottage", description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 1500, location: "Malibu, United States", country: "United States", geometry: { type: "Point", coordinates: [-118.7798, 34.0259] }, category: "Trending" },
  { title: "Modern Loft in Downtown", description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501183638710-841dd1904471?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 1200, location: "New York City, United States", country: "United States", geometry: { type: "Point", coordinates: [-74.0060, 40.7128] }, category: "Iconic Cities" },
  { title: "Mountain Retreat", description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 1000, location: "Aspen, United States", country: "United States", geometry: { type: "Point", coordinates: [-106.8175, 39.1911] }, category: "Mountains" },
  { title: "Historic Villa in Tuscany", description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 2500, location: "Florence, Italy", country: "Italy", geometry: { type: "Point", coordinates: [11.2558, 43.7696] }, category: "Farms" },
  { title: "Secluded Treehouse Getaway", description: "Live among the canopy in this unique treehouse retreat. A true nature lover's paradise.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 800, location: "Portland, United States", country: "United States", geometry: { type: "Point", coordinates: [-122.6765, 45.5231] }, category: "Camping" },
  { title: "Beachfront Paradise", description: "Step out of your door onto the powdery white sand of this beachfront villa.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 2000, location: "Cancun, Mexico", country: "Mexico", geometry: { type: "Point", coordinates: [-86.8515, 21.1619] }, category: "Amazing Pools" },
  { title: "Rustic Cabin by the Lake", description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 900, location: "Lake Tahoe, United States", country: "United States", geometry: { type: "Point", coordinates: [-120.0324, 39.0968] }, category: "Camping" },
  { title: "Luxury Penthouse with City Views", description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 3500, location: "Los Angeles, United States", country: "United States", geometry: { type: "Point", coordinates: [-118.2437, 34.0522] }, category: "Iconic Cities" },
  { title: "Ski-In/Ski-Out Chalet", description: "Hit the slopes right from your doorstep in this beautiful ski chalet in the Swiss Alps.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 3000, location: "Zermatt, Switzerland", country: "Switzerland", geometry: { type: "Point", coordinates: [7.7491, 46.0207] }, category: "Mountains" },
  { title: "Safari Lodge in the Serengeti", description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1516426122078-c23e76319801?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 4000, location: "Serengeti National Park, Tanzania", country: "Tanzania", geometry: { type: "Point", coordinates: [34.8333, -2.3333] }, category: "Trending" },
  { title: "Historic Canal House", description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic center.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 1800, location: "Amsterdam, Netherlands", country: "Netherlands", geometry: { type: "Point", coordinates: [4.9041, 52.3676] }, category: "Rooms" },
  { title: "Private Island Retreat", description: "Have an entire island to yourself for the ultimate exclusive getaway.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1559494007-9f5847c49d94?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 10000, location: "Fiji", country: "Fiji", geometry: { type: "Point", coordinates: [179.4144, -16.5782] }, category: "Amazing Pools" },
  { title: "Charming Cottage in the Cotswolds", description: "Escape to the picturesque Cotswolds in this quaint and cozy cottage with a thatched roof.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1587061949409-02df41d5e562?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 1200, location: "Cotswolds, United Kingdom", country: "United Kingdom", geometry: { type: "Point", coordinates: [-1.8839, 51.7950] }, category: "Farms" },
  { title: "Historic Brownstone in Boston", description: "Step back in time in this elegant historic brownstone located in the heart of Boston.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 2200, location: "Boston, United States", country: "United States", geometry: { type: "Point", coordinates: [-71.0589, 42.3601] }, category: "Iconic Cities" },
  { title: "Beachfront Bungalow in Bali", description: "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 1800, location: "Bali, Indonesia", country: "Indonesia", geometry: { type: "Point", coordinates: [115.1889, -8.4095] }, category: "Trending" },
  { title: "Mountain View Cabin in Banff", description: "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 1500, location: "Banff, Canada", country: "Canada", geometry: { type: "Point", coordinates: [-115.5708, 51.1784] }, category: "Mountains" },
  { title: "Art Deco Apartment in Miami", description: "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1514214246283-d427a95c5d2f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 1600, location: "Miami, United States", country: "United States", geometry: { type: "Point", coordinates: [-80.1918, 25.7617] }, category: "Rooms" },
  { title: "Tropical Villa in Phuket", description: "Escape to a tropical paradise in this luxurious villa with a spectacular infinity pool.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 3000, location: "Phuket, Thailand", country: "Thailand", geometry: { type: "Point", coordinates: [98.3923, 7.9519] }, category: "Amazing Pools" },
  { title: "Historic Castle in Scotland", description: "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged landscape.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 4000, location: "Scottish Highlands, United Kingdom", country: "United Kingdom", geometry: { type: "Point", coordinates: [-4.2247, 57.1200] }, category: "Castles" },
  { title: "Desert Oasis in Dubai", description: "Experience luxury in the middle of the desert in this opulent oasis with a private pool.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 5000, location: "Dubai, United Arab Emirates", country: "United Arab Emirates", geometry: { type: "Point", coordinates: [55.2708, 25.2048] }, category: "Amazing Pools" },
  { title: "Rustic Log Cabin in Montana", description: "Unplug and relax in this cozy log cabin surrounded by nature and majestic mountains.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 1100, location: "Montana, United States", country: "United States", geometry: { type: "Point", coordinates: [-110.3626, 46.9219] }, category: "Camping" },
  { title: "Arctic Glass Igloo", description: "Sleep under the Northern Lights in this incredible heated glass igloo in the Arctic circle.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1572259160565-388273f5ff24?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 2800, location: "Lapland, Finland", country: "Finland", geometry: { type: "Point", coordinates: [26.4952, 67.9222] }, category: "Arctic" },
  { title: "Luxury Riad in Marrakech", description: "Experience the vibrant culture of Morocco from this stunning traditional Riad with a central courtyard.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1558981420-87aa9dad1c89?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 1300, location: "Marrakech, Morocco", country: "Morocco", geometry: { type: "Point", coordinates: [-7.9811, 31.6295] }, category: "Iconic Cities" },
  { title: "Overwater Bungalow", description: "Wake up to the sound of crystal clear waves right under your bed in this romantic overwater suite.", image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" }, price: 6500, location: "Bora Bora, French Polynesia", country: "French Polynesia", geometry: { type: "Point", coordinates: [-151.7415, -16.5004] }, category: "Amazing Pools" }
];

module.exports = { data: sampleListings };